---
title: "Final Color Palettes for 2-5 groups"
author: "Dave Bosworth"
date: "3/17/2020"
output:
  html_document: 
    code_folding: hide
    toc: yes
    toc_float:
      collapsed: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Create Palettes

Load R packages necessary for this document:
```{r load packages, message = FALSE, warning = FALSE}
library(colorspace)
```

Define palettes for 2-5 colors:
```{r define palettes}
pal_two <- c("#00588B", "#F69422")
pal_three <- sequential_hcl(3, palette = "Viridis")
pal_four <- sequential_hcl(4, palette = "Viridis")
pal_five <- sequential_hcl(5, palette = "Viridis")
```

# Example Plots for all Palettes

## Two Colors

RGB values:

* Orange: 246, 148, 34
* Blue: 0, 88, 139

```{r two colors actual}
demoplot(pal_two, "spine")
```

## Three Colors

RGB values:

* Yellow: 253, 227, 51
* Light Blue: 0, 155, 149
* Purple: 75, 0, 85

```{r three colors actual}
demoplot(pal_three, "spine")
```

## Four Colors

RGB values:

* Yellow: 253, 227, 51
* Green: 0, 190, 125
* Blue: 0, 112, 148
* Purple: 75, 0, 85

```{r four colors actual}
demoplot(pal_four, "spine")
```

## Five Colors

RGB values:

* Yellow: 253, 227, 51
* Green: 83, 204, 103
* Light Blue: 0, 155, 149
* Blue: 0, 88, 139
* Purple: 75, 0, 85

```{r five colors actual}
demoplot(pal_five, "spine")
```

